In [750]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [751]:
dataset = pd.read_csv('Dataset.csv')

In [752]:
dataset.head()

Time  Api  Suhu  Kelembaban    PPM            Label
0  1:33:59    0  26.9          72  50.14  Tidak Kebakaran
1  1:34:03    0  26.8          72  50.89  Tidak Kebakaran
2  1:34:06    0  26.9          72  49.77  Tidak Kebakaran
3  1:34:10    0  26.9          72  51.64  Tidak Kebakaran
4  1:34:14    0  26.8          72  54.34  Tidak Kebakaran

In [753]:
le=LabelEncoder()
dataset["Label"]=le.fit_transform(dataset[["Label"]])

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [754]:
dataset.head()

Time  Api  Suhu  Kelembaban    PPM  Label
0  1:33:59    0  26.9          72  50.14      0
1  1:34:03    0  26.8          72  50.89      0
2  1:34:06    0  26.9          72  49.77      0
3  1:34:10    0  26.9          72  51.64      0
4  1:34:14    0  26.8          72  54.34      0

In [755]:
dataset = dataset.iloc[:,1:]
dataset.head()

Api  Suhu  Kelembaban    PPM  Label
0    0  26.9          72  50.14      0
1    0  26.8          72  50.89      0
2    0  26.9          72  49.77      0
3    0  26.9          72  51.64      0
4    0  26.8          72  54.34      0

In [756]:
x=dataset.iloc[ : , :-1]
x.head()

Api  Suhu  Kelembaban    PPM
0    0  26.9          72  50.14
1    0  26.8          72  50.89
2    0  26.9          72  49.77
3    0  26.9          72  51.64
4    0  26.8          72  54.34

In [757]:
y=dataset.iloc[ : ,-1]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Label, dtype: int64

In [758]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.1)

In [759]:
print(xtrain)

     Api  Suhu  Kelembaban     PPM
278    0  23.4          84   13.88
5      0  26.8          72   47.57
65     0  26.7          74   60.84
76     1  28.1          73  429.08
328    1  36.5          46  605.41
..   ...   ...         ...     ...
261    0  23.2          84    7.61
84     1  28.4          73  377.77
179    0  23.6          85   58.35
7      0  26.8          72   46.15
279    0  23.4          84   20.57

[333 rows x 4 columns]


In [760]:
print(xtest)

     Api  Suhu  Kelembaban      PPM
114    1  38.7          60  3271.28
332    0  35.7          45   621.83
333    0  35.5          45   607.44
148    0  23.6          84    45.79
51     0  26.8          75    50.89
63     0  26.7          74    52.52
0      0  26.9          72    50.14
126    0  40.1          58  2967.34
173    0  23.6          85    63.84
54     0  26.8          75    50.89
80     1  28.2          73   468.21
216    1  34.2          65   478.39
236    1  37.4          55   459.86
215    1  33.9          67   559.96
131    0  23.5          84    48.30
69     0  26.7          73    60.84
12     0  26.8          72    49.77
159    0  23.6          84    50.89
185    0  23.6          84    70.56
301    0  23.5          85    45.79
73     0  26.7          73    60.84
133    0  23.6          84    43.04
334    0  35.4          46   593.29
113    1  38.3          60  3231.86
155    0  23.6          84    57.53
83     1  28.3          73   456.54
166    0  23.6          84  

In [761]:
#Lebih cocok pakai ini, di bagi dulu ke xtrain dan xtest

from sklearn.preprocessing import QuantileTransformer
normscaler = QuantileTransformer()
xtrain = normscaler.fit_transform(xtrain)
xtest = normscaler.fit_transform(xtest)

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_data.py:2590: UserWarning: n_quantiles (1000) is greater than the total number of samples (333). n_quantiles is set to n_samples.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_data.py:2590: UserWarning: n_quantiles (1000) is greater than the total number of samples (38). n_quantiles is set to n_samples.
  warnings.warn(


In [762]:
print(xtrain)

[[0.         0.09337349 0.75903614 0.07228916]
 [0.         0.42620482 0.39759036 0.20783133]
 [0.         0.3313253  0.57680723 0.45481928]
 ...
 [0.         0.24246988 1.         0.43674699]
 [0.         0.42620482 0.39759036 0.17168675]
 [0.         0.09337349 0.75903614 0.0873494 ]]


In [763]:
print(xtest)

[[1.         0.94594595 0.28378378 1.        ]
 [0.         0.75675676 0.         0.83783784]
 [0.         0.72972973 0.         0.81081081]
 [0.         0.17567568 0.81081081 0.09459459]
 [0.         0.43243243 0.63513514 0.24324324]
 [0.         0.32432432 0.56756757 0.32432432]
 [0.         0.51351351 0.41891892 0.18918919]
 [0.         1.         0.21621622 0.91891892]
 [0.         0.17567568 1.         0.48648649]
 [0.         0.43243243 0.63513514 0.24324324]
 [1.         0.56756757 0.5        0.64864865]
 [1.         0.64864865 0.35135135 0.67567568]
 [1.         0.89189189 0.16216216 0.62162162]
 [1.         0.62162162 0.37837838 0.72972973]
 [0.         0.         0.81081081 0.13513514]
 [0.         0.32432432 0.5        0.43243243]
 [0.         0.43243243 0.41891892 0.16216216]
 [0.         0.17567568 0.81081081 0.24324324]
 [0.         0.17567568 0.81081081 0.51351351]
 [0.         0.         1.         0.09459459]
 [0.         0.32432432 0.5        0.43243243]
 [0.         

In [764]:
model = SVC(kernel='linear', C=1E10)

In [765]:
model.fit(xtrain, ytrain)

SVC(C=10000000000.0, kernel='linear')

In [766]:
predictions = model.predict(xtest)
print(predictions)

[1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0
 1]


In [767]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [768]:
percentage = accuracy_score(ytest,predictions)

In [769]:
res = confusion_matrix(ytest, predictions)
print(classification_report(ytest,predictions))
print("Confusion Matrix")
print(res)
print(f"Test Set: {len(xtest)}")
print(f"Accuracy = {percentage*100} %")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        18

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix
[[20  0]
 [ 0 18]]
Test Set: 38
Accuracy = 100.0 %
